### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MrHulu** [paceaux/xlsx-to-json#5]
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\xlsxToJson.py", line 69, in <module>
    main()
  File "C:\Users\Administrator\Desktop\xlsxToJson.py", line 59, in main
    workbook = xlrd.open_workbook(filename)
  File "C:\Python\lib\site-packages\xlrd\__init__.py", line 170, in open_workbook
    raise XLRDError(FILE_FORMAT_DESCRIPTIONS[file_format]+'; not supported')
xlrd.biffh.XLRDError: Excel xlsx file; not supported

**Comment by paceaux** [comment]
could you provide a sample of the file you tried to run with this?

**Comment by MrHulu** [comment]
I would like to know if there are any requirements for the format of xlsx files? Thanks!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "paceaux/xlsx-to-json"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月1日(星期五) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [paceaux/xlsx-to-json] Not working (Issue #5)





 
could you provide a sample of the file you tried to run with this?

**Comment by paceaux** [comment]
This is the first thing I ever wrote in python, and I wrote it 6 years ago for a use-case I haven't needed since then. 

Let me find a machine around the house with Excel on it, and see what I can do. I honestly don't know what those requirements would've been because I had absolutely no clue what I was doing at the time.

**Comment by MrHulu** [comment]
wow! You started writing python 6 years ago, that's excellent. 6 years ago&nbsp;&nbsp;I was just a kid.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月10日(星期天) 中午11:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [paceaux/xlsx-to-json] Not working (Issue #5)





 
This is the first thing I ever wrote in python, and I wrote it 6 years ago for a use-case I haven't needed since then.
 
Let me find a machine around the house with Excel on it, and see what I can do. I honestly don't know what those requirements would've been because I had absolutely no clue what I was doing at the time.
